services:
  postgres:
    image: postgres:16-alpine
    container_name: salary-validation-db
    environment:
      POSTGRES_DB: salary_validation_db
      POSTGRES_USER: salary_admin
      POSTGRES_PASSWORD: admin_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
