spring:
  application:
    name: salary-validation-service

  datasource:
    url: jdbc:postgresql://localhost:5432/salary_validation_db
    username: salary_admin
    password: admin_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

salary:
  confirmation:
    start-day: 25
    end-day: 5
